#The structure below maps your hardware to an alias in iox and applies permissions so that only
#your plugin can access that hardware.
#Things you MUST CHANGE:
#1. The value for "vendor"
#2. The value for "product"
#3. Replace pg3.my_hardware with a uniqe identifier for your hardware 
#4. Rename this file and put the name in the plugin.meta['hardwareConfig']
### DO NOT CHANGE ANYHTING ELSE ###

attach 100 {
        match "vendor" "0x10c4";
        match "product" "0xea60";
        action "chown UDX_OWNER_PLACE_HOLDER /dev/tty$ttyname";
        action "chmod UDX_PERMISSION_PLACE_HOLDER /dev/tty$ttyname";
        action "/usr/local/etc/udx.d/static/pg3.serial.dev.ops /dev/tty$ttyname pg3.my_hardware";
};
